=== jkstuecher/5GuysCalcTypeScript/5GCalc/Data/Items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Items" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Items">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="ItemName " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAABXjXE78OQcQL4srH+1NAxaAAAAAAtwQG77UuRAOQMCALCxVgBJAHQA
ZQBtAHMAAAAAAAAA1BOWlCzdiESNfkcB/ITmtQcAAABXjXE78OQcQL4srH+1NAxa
UwBlAGMAdABpAG8AbgBPAHIAZABlAHIAAAAAAAAAS8NR7t7NPkSp3dc9m/XrXgcA
AABXjXE78OQcQL4srH+1NAxaSQB0AGUAbQBOAGEAbQBlAAAAAAAAAJe5zk1IDvZG
tAe/OdzGZ6wHAAAAV41xO/DkHEC+LKx/tTQMWlMAZQByAHYAaQBuAGcAUwBpAHoA
ZQAAAAAAAACED4T4+sW1QKUpZBlimi75BwAAAFeNcTvw5BxAviysf7U0DFpDAGEA
bABvAHIAaQBlAHMAAAAAAAAAyveLSf/MaUq57+Qq8oOPMAcAAABXjXE78OQcQL4s
rH+1NAxaQwBhAGwAbwByAGkAZQBzAEYAcgBvAG0ARgBhAHQAAAAAAAAAtBUrMJcT
fEiw+uSyNCcS/wcAAABXjXE78OQcQL4srH+1NAxaVABvAHQAYQBsAEYAYQB0AAAA
AAAAAJEcDHwejPpDqz5f6vWS/9IHAAAAV41xO/DkHEC+LKx/tTQMWlMAYQB0AHUA
cgBhAHQAZQBkAEYAYQB0AAAAAAAAAKTFjT8t8nhOqDr2K9GttOIHAAAAV41xO/Dk
HEC+LKx/tTQMWlQAcgBhAG4AcwBGAGEAdAAAAAAAAABlUg9dKVwLToWGZT0W71sh
BwAAAFeNcTvw5BxAviysf7U0DFpDAGgAbwBsAGUAcwB0AGUAcgBvAGwAAAAAAAAA
cjoAx05Zz0KJFyfLqqvW/gcAAABXjXE78OQcQL4srH+1NAxaUwBvAGQAaQB1AG0A
AAAAAAAAA2dexoL850SGRGvFJ9OFaAcAAABXjXE78OQcQL4srH+1NAxaQwBhAHIA
YgBzAAAAAAAAAHaMecadOsFLtQHF+qblRWEHAAAAV41xO/DkHEC+LKx/tTQMWkYA
aQBiAGUAcgAAAAAAAABFFb7CRKaLS4CzTnUVb2IdBwAAAFeNcTvw5BxAviysf7U0
DFpTAHUAZwBhAHIAAAAAAAAAnWSHyyy7E02RuzLCT4MsXwcAAABXjXE78OQcQL4s
rH+1NAxaUAByAG8AdABlAGkAbgAAAAAAAABF/ECjAv09QYnLkoH4Y8rtBwAAAFeN
cTvw5BxAviysf7U0DFpTAGUAcgB2AGkAbgBnAFMAaQB6AGUAVQBuAGkAdAAAAAAA
AAAyzKDM4yEaSr1HGcYdlD21BwAAAFeNcTvw5BxAviysf7U0DFpTAGUAYwB0AGkA
bwBuAAAAAAAAAI6laNcywEdFnP1m8UD3nHoHAAAAV41xO/DkHEC+LKx/tTQMWkkA
dABlAG0ATwByAGQAZQByAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABAAAAAAA
AAAAAAAAAAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="GUID" type="9" value="V41xO/DkHEC+LKx/tTQMWg==
"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="OrderBy" type="12" value="[Items].[SectionOrder]"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="ItemName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="S8NR7t7NPkSp3dc9m/XrXg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3705"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ServingSize" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="l7nOTUgO9ka0B7853MZnrA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Calories" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="hA+E+PrFtUClKWQZYpou+Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1545"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="CaloriesFromFat" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="yveLSf/MaUq57+Qq8oOPMA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2130"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="TotalFat" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="tBUrMJcTfEiw+uSyNCcS/w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1590"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="SaturatedFat" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="kRwMfB6M+kOrPl/q9ZL/0g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="TransFat" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="pMWNPy3yeE6oOvYr0a204g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Cholesterol" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="ZVIPXSlcC06FhmU9Fu9bIQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Sodium" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="cjoAx05Zz0KJFyfLqqvW/g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Carbs" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="A2dexoL850SGRGvFJ9OFaA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="11"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Fiber" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="dox5xp06wUu1AcX6puVFYQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="12"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Sugar" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="RRW+wkSmi0uAs051FW9iHQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="13"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Protein" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="nWSHyyy7E02RuzLCT4MsXw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="1650"/>
<od:fieldProperty name="ColumnOrder" type="3" value="14"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="2"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ServingSizeUnit" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="RfxAowL9PUGJy5KB+GPK7Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2175"/>
<od:fieldProperty name="ColumnOrder" type="3" value="15"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Section" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="MsygzOMhGkq9RxnGHZQ9tQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2340"/>
<od:fieldProperty name="ColumnOrder" type="3" value="16"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="SectionOrder" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="17"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="ItemOrder" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== jkstuecher/5GuysCalcTypeScript/5GCalc/Data/Items.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Items.xsd" generated="2013-12-15T20:42:51">
<Items>
<ItemName>Bacon Cheeseburger</ItemName>
<ServingSize>317</ServingSize>
<Calories>920</Calories>
<CaloriesFromFat>560</CaloriesFromFat>
<TotalFat>62</TotalFat>
<SaturatedFat>29.5</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>180</Cholesterol>
<Sodium>1310</Sodium>
<Carbs>40</Carbs>
<Fiber>2</Fiber>
<Sugar>9</Sugar>
<Protein>51</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Burgers</Section>
<SectionOrder>1</SectionOrder>
<ItemOrder>4</ItemOrder>
</Items>
<Items>
<ItemName>Hamburger</ItemName>
<ServingSize>265</ServingSize>
<Calories>700</Calories>
<CaloriesFromFat>400</CaloriesFromFat>
<TotalFat>43</TotalFat>
<SaturatedFat>19.5</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>125</Cholesterol>
<Sodium>430</Sodium>
<Carbs>39</Carbs>
<Fiber>2</Fiber>
<Sugar>8</Sugar>
<Protein>39</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Burgers</Section>
<SectionOrder>1</SectionOrder>
<ItemOrder>1</ItemOrder>
</Items>
<Items>
<ItemName>Cheeseburger</ItemName>
<ServingSize>303</ServingSize>
<Calories>840</Calories>
<CaloriesFromFat>500</CaloriesFromFat>
<TotalFat>55</TotalFat>
<SaturatedFat>26.5</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>165</Cholesterol>
<Sodium>1050</Sodium>
<Carbs>40</Carbs>
<Fiber>2</Fiber>
<Sugar>9</Sugar>
<Protein>47</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Burgers</Section>
<SectionOrder>1</SectionOrder>
<ItemOrder>2</ItemOrder>
</Items>
<Items>
<ItemName>Bacon Burger</ItemName>
<ServingSize>279</ServingSize>
<Calories>780</Calories>
<CaloriesFromFat>460</CaloriesFromFat>
<TotalFat>50</TotalFat>
<SaturatedFat>22.5</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>140</Cholesterol>
<Sodium>690</Sodium>
<Carbs>39</Carbs>
<Fiber>2</Fiber>
<Sugar>8</Sugar>
<Protein>43</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Burgers</Section>
<SectionOrder>1</SectionOrder>
<ItemOrder>3</ItemOrder>
</Items>
<Items>
<ItemName>Little Cheeseburger</ItemName>
<ServingSize>190</ServingSize>
<Calories>550</Calories>
<CaloriesFromFat>290</CaloriesFromFat>
<TotalFat>32</TotalFat>
<SaturatedFat>15</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>85</Cholesterol>
<Sodium>690</Sodium>
<Carbs>39.5</Carbs>
<Fiber>2</Fiber>
<Sugar>8</Sugar>
<Protein>27</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Little Burgers</Section>
<SectionOrder>2</SectionOrder>
<ItemOrder>2</ItemOrder>
</Items>
<Items>
<ItemName>Little Bacon Burger</ItemName>
<ServingSize>185</ServingSize>
<Calories>560</Calories>
<CaloriesFromFat>300</CaloriesFromFat>
<TotalFat>33</TotalFat>
<SaturatedFat>14.5</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>80</Cholesterol>
<Sodium>640</Sodium>
<Carbs>39</Carbs>
<Fiber>2</Fiber>
<Sugar>8</Sugar>
<Protein>27</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Little Burgers</Section>
<SectionOrder>2</SectionOrder>
<ItemOrder>3</ItemOrder>
</Items>
<Items>
<ItemName>Little Hamburger</ItemName>
<ServingSize>171</ServingSize>
<Calories>480</Calories>
<CaloriesFromFat>240</CaloriesFromFat>
<TotalFat>26</TotalFat>
<SaturatedFat>11.5</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>65</Cholesterol>
<Sodium>380</Sodium>
<Carbs>39</Carbs>
<Fiber>2</Fiber>
<Sugar>8</Sugar>
<Protein>15</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Little Burgers</Section>
<SectionOrder>2</SectionOrder>
<ItemOrder>1</ItemOrder>
</Items>
<Items>
<ItemName>Little Bacon Cheeseburger</ItemName>
<ServingSize>204</ServingSize>
<Calories>630</Calories>
<CaloriesFromFat>350</CaloriesFromFat>
<TotalFat>39</TotalFat>
<SaturatedFat>18</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>100</Cholesterol>
<Sodium>950</Sodium>
<Carbs>39.5</Carbs>
<Fiber>2</Fiber>
<Sugar>8</Sugar>
<Protein>31</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Little Burgers</Section>
<SectionOrder>2</SectionOrder>
<ItemOrder>4</ItemOrder>
</Items>
<Items>
<ItemName>Bacon Cheese Dog</ItemName>
<ServingSize>200</ServingSize>
<Calories>695</Calories>
<CaloriesFromFat>425</CaloriesFromFat>
<TotalFat>48</TotalFat>
<SaturatedFat>22</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>96</Cholesterol>
<Sodium>1700</Sodium>
<Carbs>40</Carbs>
<Fiber>2</Fiber>
<Sugar>8.5</Sugar>
<Protein>26</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Dogs</Section>
<SectionOrder>3</SectionOrder>
<ItemOrder>4</ItemOrder>
</Items>
<Items>
<ItemName>Hot Dog</ItemName>
<ServingSize>167</ServingSize>
<Calories>545</Calories>
<CaloriesFromFat>315</CaloriesFromFat>
<TotalFat>35</TotalFat>
<SaturatedFat>15.5</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>61</Cholesterol>
<Sodium>1130</Sodium>
<Carbs>40</Carbs>
<Fiber>2</Fiber>
<Sugar>8</Sugar>
<Protein>18</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Dogs</Section>
<SectionOrder>3</SectionOrder>
<ItemOrder>1</ItemOrder>
</Items>
<Items>
<ItemName>Cheese Dog</ItemName>
<ServingSize>186</ServingSize>
<Calories>615</Calories>
<CaloriesFromFat>365</CaloriesFromFat>
<TotalFat>41</TotalFat>
<SaturatedFat>19</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>81</Cholesterol>
<Sodium>1440</Sodium>
<Carbs>40.5</Carbs>
<Fiber>2</Fiber>
<Sugar>8.5</Sugar>
<Protein>22</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Dogs</Section>
<SectionOrder>3</SectionOrder>
<ItemOrder>2</ItemOrder>
</Items>
<Items>
<ItemName>Bacon Dog</ItemName>
<ServingSize>181</ServingSize>
<Calories>625</Calories>
<CaloriesFromFat>375</CaloriesFromFat>
<TotalFat>42</TotalFat>
<SaturatedFat>18.5</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>76</Cholesterol>
<Sodium>1390</Sodium>
<Carbs>40</Carbs>
<Fiber>2</Fiber>
<Sugar>8</Sugar>
<Protein>22</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Dogs</Section>
<SectionOrder>3</SectionOrder>
<ItemOrder>3</ItemOrder>
</Items>
<Items>
<ItemName>Cheese Veggie</ItemName>
<ServingSize>228</ServingSize>
<Calories>510</Calories>
<CaloriesFromFat>190</CaloriesFromFat>
<TotalFat>21</TotalFat>
<SaturatedFat>10</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>45</Cholesterol>
<Sodium>1350</Sodium>
<Carbs>61</Carbs>
<Fiber>2</Fiber>
<Sugar>14</Sugar>
<Protein>20</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Sandwiches</Section>
<SectionOrder>4</SectionOrder>
<ItemOrder>2</ItemOrder>
</Items>
<Items>
<ItemName>Grilled Cheese</ItemName>
<ServingSize>110</ServingSize>
<Calories>470</Calories>
<CaloriesFromFat>230</CaloriesFromFat>
<TotalFat>26</TotalFat>
<SaturatedFat>9</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>35</Cholesterol>
<Sodium>715</Sodium>
<Carbs>41</Carbs>
<Fiber>2</Fiber>
<Sugar>10</Sugar>
<Protein>11</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Sandwiches</Section>
<SectionOrder>4</SectionOrder>
<ItemOrder>3</ItemOrder>
</Items>
<Items>
<ItemName>BLT</ItemName>
<ServingSize>201</ServingSize>
<Calories>533</Calories>
<CaloriesFromFat>300</CaloriesFromFat>
<TotalFat>34</TotalFat>
<SaturatedFat>12</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>45</Cholesterol>
<Sodium>931</Sodium>
<Carbs>42</Carbs>
<Fiber>3</Fiber>
<Sugar>10</Sugar>
<Protein>15</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Sandwiches</Section>
<SectionOrder>4</SectionOrder>
<ItemOrder>4</ItemOrder>
</Items>
<Items>
<ItemName>Veggie</ItemName>
<ServingSize>209</ServingSize>
<Calories>440</Calories>
<CaloriesFromFat>140</CaloriesFromFat>
<TotalFat>15</TotalFat>
<SaturatedFat>6</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>25</Cholesterol>
<Sodium>1040</Sodium>
<Carbs>60</Carbs>
<Fiber>2</Fiber>
<Sugar>14</Sugar>
<Protein>15.5</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Sandwiches</Section>
<SectionOrder>4</SectionOrder>
<ItemOrder>1</ItemOrder>
</Items>
<Items>
<ItemName>Bunless Bacon Cheeseburger</ItemName>
<ServingSize>240</ServingSize>
<Calories>660</Calories>
<CaloriesFromFat>480</CaloriesFromFat>
<TotalFat>53</TotalFat>
<SaturatedFat>26</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>175</Cholesterol>
<Sodium>980</Sodium>
<Carbs>1</Carbs>
<Fiber>0</Fiber>
<Sugar>1</Sugar>
<Protein>44</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Bunless Burgers</Section>
<SectionOrder>5</SectionOrder>
<ItemOrder>4</ItemOrder>
</Items>
<Items>
<ItemName>Bunless Bacon Burger</ItemName>
<ServingSize>202</ServingSize>
<Calories>520</Calories>
<CaloriesFromFat>380</CaloriesFromFat>
<TotalFat>41</TotalFat>
<SaturatedFat>19</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>135</Cholesterol>
<Sodium>360</Sodium>
<Carbs>0</Carbs>
<Fiber>0</Fiber>
<Sugar>0</Sugar>
<Protein>36</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Bunless Burgers</Section>
<SectionOrder>5</SectionOrder>
<ItemOrder>3</ItemOrder>
</Items>
<Items>
<ItemName>Bunless Hamburger</ItemName>
<ServingSize>188</ServingSize>
<Calories>440</Calories>
<CaloriesFromFat>320</CaloriesFromFat>
<TotalFat>34</TotalFat>
<SaturatedFat>16</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>120</Cholesterol>
<Sodium>100</Sodium>
<Carbs>0</Carbs>
<Fiber>0</Fiber>
<Sugar>0</Sugar>
<Protein>32</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Bunless Burgers</Section>
<SectionOrder>5</SectionOrder>
<ItemOrder>1</ItemOrder>
</Items>
<Items>
<ItemName>Bunless Cheeseburger</ItemName>
<ServingSize>226</ServingSize>
<Calories>580</Calories>
<CaloriesFromFat>420</CaloriesFromFat>
<TotalFat>46</TotalFat>
<SaturatedFat>23</SaturatedFat>
<TransFat>0</TransFat>
<Cholesterol>160</Cholesterol>
<Sodium>720</Sodium>
<Carbs>1</Carbs>
<Fiber>0</Fiber>
<Sugar>1</Sugar>
<Protein>40</Protein>
<ServingSizeUnit>g</ServingSizeUnit>
<Section>Bunless Burgers</Section>
<SectionOrder>5</SectionOrder>
<ItemOrder>2</ItemOrder>
</Items>
<Items>
<ItemName>Bunless Little Bacon Cheeseburger</ItemName>
<ServingSize>127</ServingSize>
<Calories>370</Calories>
<CaloriesFromFat>270</CaloriesFromFat>
<TotalFat>30</TotalFat>
<SaturatedFat>14.5</SaturatedFat>
